package form

// Submitter ...
type Submitter interface {
	// SendSimpleForm ...
	SendSimpleForm(f SimpleForm) error
	// SendModalForm ...
	SendModalForm(f ModalForm) error
	// SendCustomForm ...
	SendCustomForm(f CustomForm) error
}
